apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: notice_service-applicationset
  namespace: default
spec:
  generators:
    - list:
        elements:
          - name: notice_service-appset
            repoURL: 'https://github.com/maengchanho/notice_servise.git'
            targetRevision: HEAD
            path: 'k8s'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true