name: Flask CI/CD

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read
  packages: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run lint for all services
      run: |
        pip install flake8
        flake8 notice_service.py models.py config.py

    - name: Debug .env file
      run: cat .env

    - name: Run test for all services
      run: |
        pip install pytest
        pip install python-dotenv
        pytest --disable-warnings
        pytest notice_service_test.py
        pytest models_test.py
        pytest config_test.py
  
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/notice_service:latest
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using docker-compose
      run: |
        docker compose pull
        docker compose up -d
