name: CI

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run lint for all services
      run: |
        pip install flake8
        flake8 notice_service.py

    - name: Run test for all services
      run: |
        pip install pytest
        pytest --disable-warnings
        pytest notice_service_test.py
  
